export const GEORGIAN_REGIONS = [
  { value: 'tbilisi', key: 'region_tbilisi' },
  { value: 'adjara', key: 'region_adjara' },
  { value: 'imereti', key: 'region_imereti' },
  { value: 'kakheti', key: 'region_kakheti' },
  { value: 'shida_kartli', key: 'region_shida_kartli' },
  { value: 'kvemo_kartli', key: 'region_kvemo_kartli' },
  { value: 'samegrelo', key: 'region_samegrelo' },
  { value: 'guria', key: 'region_guria' },
  { value: 'racha', key: 'region_racha' },
  { value: 'mtskheta', key: 'region_mtskheta' },
  { value: 'samtskhe', key: 'region_samtskhe' },
  { value: 'abkhazia', key: 'region_abkhazia' },
] as const;

export const CITY_REGION_MAP: Record<string, string> = {
  თბილისი: 'tbilisi',
  ბათუმი: 'adjara',
  ქობულეთი: 'adjara',
  ქუთაისი: 'imereti',
  ზესტაფონი: 'imereti',
  სამტრედია: 'imereti',
  წყალტუბო: 'imereti',
  საჩხერე: 'imereti',
  ჭიათურა: 'imereti',
  ტყიბული: 'imereti',
  რუსთავი: 'kvemo_kartli',
  მარნეული: 'kvemo_kartli',
  ბოლნისი: 'kvemo_kartli',
  გარდაბანი: 'kvemo_kartli',
  თეთრიწყარო: 'kvemo_kartli',
  დმანისი: 'kvemo_kartli',
  წალკა: 'kvemo_kartli',
  გორი: 'shida_kartli',
  კასპი: 'shida_kartli',
  ხაშური: 'shida_kartli',
  ზუგდიდი: 'samegrelo',
  ფოთი: 'samegrelo',
  სენაკი: 'samegrelo',
  თელავი: 'kakheti',
  გურჯაანი: 'kakheti',
  საგარეჯო: 'kakheti',
  სიღნაღი: 'kakheti',
  დედოფლისწყარო: 'kakheti',
  ლაგოდეხი: 'kakheti',
  ახალციხე: 'samtskhe',
  ბორჯომი: 'samtskhe',
  მცხეთა: 'mtskheta',
  ოზურგეთი: 'guria',
};

/** პოპულარული ქალაქები — მოდალის ბადეში (ზემოდან ქვემოთ, მარცხნიდან მარჯვნივ) */
export const POPULAR_CITIES_GRID = [
  'თბილისი',
  'ბათუმი',
  'ქუთაისი',
  'რუსთავი',
  'ფოთი',
  'ზუგდიდი',
  'თელავი',
  'გორი',
  'მცხეთა',
] as const;

export const POPULAR_CITIES = [
  ...POPULAR_CITIES_GRID,
  'ახალციხე',
  'ოზურგეთი',
  'მარნეული',
  'კასპი',
  'ზესტაფონი',
  'ხაშური',
  'სამტრედია',
  'სენაკი',
  'ქობულეთი',
  'წყალტუბო',
  'ბორჯომი',
  'საჩხერე',
  'ჭიათურა',
  'ტყიბული',
  'გურჯაანი',
  'საგარეჯო',
  'სიღნაღი',
  'დედოფლისწყარო',
  'ლაგოდეხი',
  'ბოლნისი',
  'გარდაბანი',
  'თეთრიწყარო',
  'დმანისი',
  'წალკა',
];

/** რეგიონის არჩევა ქალაქის გარეშე */
export const TBILISI_SURROUNDINGS_LABEL = 'თბილისის შემოგარენი';
